#!/bin/bash

set -euo pipefail

# Setup environment
cd ../ || exit  # Go to the root directory of the repo
source setup_env.sh

# Reuse preprocessed self-distilled GSM8K datasets generated by
# run_train_e2d_gsm8k_freeze_bottom_self_distill.sh
MAX_SEQ_LEN=1024
DISTILL_DATA_ROOT=${DISTILL_DATA_ROOT:-/data/shared_data/hankun/datasets/gsm8k_qwen3_1p7b_selfdistill_maxlen${MAX_SEQ_LEN}}
DISTILL_TRAIN_PATH=${DISTILL_TRAIN_PATH:-${DISTILL_DATA_ROOT}/train_preprocessed}
DISTILL_EVAL_PATH=${DISTILL_EVAL_PATH:-${DISTILL_DATA_ROOT}/eval_preprocessed}

if [[ ! -d "${DISTILL_TRAIN_PATH}" || ! -d "${DISTILL_EVAL_PATH}" ]]; then
  echo "[Error] Missing preprocessed self-distill dataset paths."
  echo "  train: ${DISTILL_TRAIN_PATH}"
  echo "  eval : ${DISTILL_EVAL_PATH}"
  echo "Please run run_train_e2d_gsm8k_freeze_bottom_self_distill.sh first or set DISTILL_*_PATH manually."
  exit 1
fi

# Model arch
BLOCK_SIZE=4
EVAL_BLOCK_SIZE=4
N_ENCODER_LAYERS=28
ENCODER_TOP_LAYERS=false
N_DECODER_LAYERS=2
DECODER_TOP_LAYERS=true
REINIT_ENCODER=false
REINIT_DECODER=false
TIE_WEIGHTS=true
FREEZE_ENCODER=false
ENCODER_CAUSAL_MASK=false

# Hyperparameters
LR=1e-4
WARMUP_DURATION="100ba"
ALPHA_F=0.5
BATCH_SIZE=1
MAX_DURATION=${MAX_DURATION:-30000ba}
PRECISION="amp_bf16"

PRETRAINED_MODEL_NAME_OR_PATH=${PRETRAINED_MODEL_NAME_OR_PATH:-Qwen/Qwen3-1.7B}
TRAIN_ON_CONTEXT=false

TAG="e2d_adapter_self_distill"
if [ "${ENCODER_TOP_LAYERS}" == "true" ]; then
  ENC_LAYERS="TOPenc${N_ENCODER_LAYERS}"
else
  ENC_LAYERS="enc${N_ENCODER_LAYERS}"
fi
if [ "${DECODER_TOP_LAYERS}" == "true" ]; then
  DEC_LAYERS="TOPdec${N_DECODER_LAYERS}"
else
  DEC_LAYERS="dec${N_DECODER_LAYERS}"
fi

# get time stamp
TIMESTAMP=$(date +"%Y%m%d_%H%M%S")

RUN_NAME=gsm8k-self-distill-adapter-${TIMESTAMP}

MICRO_BATCH_SIZE=1
NUM_WORKERS=0

if [ -z "${CUDA_VISIBLE_DEVICES:-}" ]; then
  NUM_VISIBLE_DEVICES=1
else
  NUM_VISIBLE_DEVICES=$(echo "${CUDA_VISIBLE_DEVICES}" | awk -F',' '{print NF}')
fi

uv run composer -n ${NUM_VISIBLE_DEVICES} scripts/composer_scripts/train_discrete_denoiser.py \
  run_name=${RUN_NAME} \
  pretrained_model_name_or_path=${PRETRAINED_MODEL_NAME_OR_PATH} \
  dataset@train_dataset=ultrachat_distill_train \
  dataset@eval_dataset=ultrachat_distill_eval \
  train_dataset.dataset_path=${DISTILL_TRAIN_PATH} \
  eval_dataset.dataset_path=${DISTILL_EVAL_PATH} \
  composer.optimizer.lr=${LR} \
  composer.trainer.precision=${PRECISION} \
  composer.trainer.eval_interval="2000ba" \
  composer.trainer.max_duration=${MAX_DURATION} \
  composer.trainer.save_num_checkpoints_to_keep=1 \
  composer/lr_scheduler=cosine_annealing_with_warmup \
  composer.lr_scheduler.t_warmup=${WARMUP_DURATION} \
  composer.lr_scheduler.alpha_f=${ALPHA_F} \
  model=e2d \
  model.config.attn_backend="sdpa" \
  training.compile_backbone=false \
  model.config.length=${MAX_SEQ_LEN} \
  model/backbone@model.config.backbone_config=llm_as_encoder_decoder_share_kv_adapter \
  model.config.backbone_config.use_encoder_causal_mask=${ENCODER_CAUSAL_MASK} \
  model.config.backbone_config.num_encoder_layers=${N_ENCODER_LAYERS} \
  model.config.backbone_config.num_decoder_layers=${N_DECODER_LAYERS} \
  model.config.backbone_config.tie_encoder_decoder_weights=${TIE_WEIGHTS} \
  model.config.backbone_config.freeze_encoder=${FREEZE_ENCODER} \
  model.config.backbone_config.reinit_decoder=${REINIT_DECODER} \
  model.config.backbone_config.reinit_encoder=${REINIT_ENCODER} \
  model.config.backbone_config.keep_top_decoder_layers=${DECODER_TOP_LAYERS} \
  model.config.backbone_config.keep_top_encoder_layers=${ENCODER_TOP_LAYERS} \
  model.config.backbone_config.use_gradient_checkpointing=false \
  training.global_batch_size=${BATCH_SIZE} \
  training.grad_accum=$(( BATCH_SIZE / NUM_VISIBLE_DEVICES / MICRO_BATCH_SIZE )) \
  block_size=${BLOCK_SIZE} \
  eval_block_size=${EVAL_BLOCK_SIZE} \
  training.antithetic_sampling=false \
  hydra.run.dir=/data/shared_data/hankun/outputs/${RUN_NAME} \
  composer.trainer.save_interval="2000ba" \
  composer.loggers.name=${RUN_NAME} \
  train_dataloader.num_workers=${NUM_WORKERS} \
  composer.callbacks.hf_compatible_checkpointing.disable_hf=true \
  composer.callbacks.save_best_checkpointing.save_local=false \
  eval_dataloader.batch_size=1 \
  model.config.train_on_context=${TRAIN_ON_CONTEXT} \
  +model.config.nullify_self_attn=false
