#!/usr/bin/env python3
"""Self-distill UltraChat user prompts with unpadded batch-one greedy decoding.

The dataset's assistant replies are never used as targets. Every completion is
generated by the unchanged target model, and its original token IDs are saved.
"""

from __future__ import annotations

import argparse
from datetime import datetime, timezone
import hashlib
import json
import os
from pathlib import Path
import sys
from typing import Any

if __package__ in (None, ""):
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from scripts.generate_gsm8k_selfdistill import (
    atomic_json,
    generate_prompt_row,
    load_resume_rows,
    write_dataset,
)


JSONL_STEM = "ultrachat_qwen3_1p7b_selfdistill_bsz1"
DEFAULT_DATA_ROOT = Path("/data/shared_data/hankun/datasets/ultrachat_qwen3_1p7b_selfdistill_bsz1_maxlen1024")


def extract_prompt_messages(example: dict) -> list[dict[str, str]] | None:
    """Prefer UltraChat's prompt column; otherwise take only its first user turn."""
    prompt = example.get("prompt")
    if isinstance(prompt, str) and prompt.strip():
        return [{"role": "user", "content": prompt.strip()}]
    messages = example.get("messages")
    if isinstance(messages, str):
        try:
            messages = json.loads(messages)
        except json.JSONDecodeError:
            return None
    if not isinstance(messages, list):
        return None
    for message in messages:
        if not isinstance(message, dict) or message.get("role") != "user":
            continue
        content = message.get("content")
        if not isinstance(content, str) or not content.strip():
            return None
        return [{"role": "user", "content": content.strip()}]
    return None


def build_prompt(example: dict, tokenizer: Any) -> str | None:
    messages = extract_prompt_messages(example)
    if messages is None:
        return None
    return tokenizer.apply_chat_template(
        messages, tokenize=False, add_generation_prompt=True, enable_thinking=False,
    )


def generate_row(
    source_index: int,
    example: dict,
    tokenizer: Any,
    model: Any,
    *,
    source_split: str,
    source_row_index: int,
    max_prompt_tokens: int,
    max_completion_tokens: int,
    device: str,
) -> dict | None:
    prompt = build_prompt(example, tokenizer)
    if prompt is None:
        return None
    generated = generate_prompt_row(
        source_index, prompt, tokenizer, model,
        max_prompt_tokens=max_prompt_tokens, max_completion_tokens=max_completion_tokens,
        device=device,
    )
    if generated is None:
        return None
    return {
        "source_index": source_index, "source_split": source_split,
        "source_row_index": source_row_index,
        "prompt_messages": extract_prompt_messages(example), **generated,
    }


def source_location(source_index: int, sources: dict) -> tuple[str, int]:
    remaining = source_index
    for split, dataset in sources.items():
        if 0 <= remaining < len(dataset):
            return split, remaining
        remaining -= len(dataset)
    raise ValueError(f"Source index {source_index} is outside the configured UltraChat splits")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data-root", type=Path, default=DEFAULT_DATA_ROOT)
    parser.add_argument("--model-name-or-path", default="Qwen/Qwen3-1.7B")
    parser.add_argument("--max-length", type=int, default=1024)
    parser.add_argument("--device", default="cuda")
    parser.add_argument("--dtype", choices=("bfloat16", "float32", "float16"), default="bfloat16")
    parser.add_argument("--attn-implementation", choices=("sdpa", "eager", "flash_attention_2"), default="sdpa")
    parser.add_argument("--source-dataset", default="HuggingFaceH4/ultrachat_200k")
    parser.add_argument("--source-config", default=None)
    parser.add_argument("--source-splits", nargs="+", default=["train_sft", "train_gen"])
    parser.add_argument("--max-samples", type=int, default=0, help="0 uses all configured source splits")
    parser.add_argument("--eval-ratio", type=float, default=0.02)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--progress-every", type=int, default=25)
    parser.add_argument("--local-files-only", action="store_true")
    args = parser.parse_args()
    if args.max_length < 2 or args.max_samples < 0 or args.max_samples == 1 or not 0 < args.eval_ratio < 1 or args.progress_every < 1:
        parser.error("Invalid length, sample count (must be zero or >=2), eval ratio, or progress interval")
    if len(set(args.source_splits)) != len(args.source_splits):
        parser.error("Source splits must be unique")

    import torch
    import transformers
    from datasets import DownloadConfig, load_dataset
    from transformers import AutoModelForCausalLM, AutoTokenizer

    # Reject legacy or unrelated outputs before loading a model or generating.
    # Reusing existing legacy UltraChat data is the training launcher's job.
    root = args.data_root
    metadata_path = root / "selfdistill_metadata.json"
    previous = None
    if metadata_path.exists():
        previous = json.loads(metadata_path.read_text(encoding="utf-8"))
        if previous.get("prompt_format") != "ultrachat" or previous.get("jsonl_stem") != JSONL_STEM:
            raise ValueError(f"Refusing to overwrite a different dataset in {root}; select a new output directory")
    elif root.exists() and any(root.iterdir()):
        raise ValueError(f"Refusing to use a nonempty directory without generation metadata: {root}")
    if args.device.startswith("cuda") and not torch.cuda.is_available():
        raise RuntimeError("CUDA is unavailable; no distillation started. Run this command on the verifier's GPU host.")

    tokenizer = AutoTokenizer.from_pretrained(args.model_name_or_path, local_files_only=args.local_files_only)
    sources = {
        split: load_dataset(
            args.source_dataset, args.source_config, split=split,
            download_config=DownloadConfig(local_files_only=args.local_files_only),
        )
        for split in args.source_splits
    }
    model = AutoModelForCausalLM.from_pretrained(
        args.model_name_or_path, torch_dtype=getattr(torch, args.dtype),
        attn_implementation=args.attn_implementation, local_files_only=args.local_files_only,
    ).to(args.device).eval()
    source_rows = sum(len(source) for source in sources.values())
    metadata = {
        "schema_version": 1, "jsonl_stem": JSONL_STEM, "prompt_format": "ultrachat",
        "max_length": args.max_length, "max_prompt_tokens": args.max_length // 2,
        "max_completion_tokens": args.max_length // 2,
        "model_name_or_path": args.model_name_or_path,
        "model_commit_hash": getattr(model.config, "_commit_hash", None),
        "dtype": args.dtype, "attn_implementation": args.attn_implementation,
        "device_type": torch.device(args.device).type,
        "batch_size": 1, "use_cache": True, "do_sample": False, "num_beams": 1,
        "padding": False, "add_special_tokens": False,
        "chat_template_kwargs": {"enable_thinking": False, "add_generation_prompt": True},
        "chat_template_sha256": hashlib.sha256(tokenizer.chat_template.encode()).hexdigest(),
        "prompt_prefix": "",
        "eos_token_id": tokenizer.eos_token_id, "pad_token_id": tokenizer.pad_token_id,
        "source_dataset": args.source_dataset, "source_config": args.source_config,
        "source_splits": args.source_splits,
        "source_fingerprints": {split: getattr(source, "_fingerprint", None) for split, source in sources.items()},
        "source_rows_by_split": {split: len(source) for split, source in sources.items()},
        "source_rows": source_rows, "max_samples": args.max_samples,
        "split_seed": args.seed, "eval_ratio": args.eval_ratio,
        "torch_version": torch.__version__, "transformers_version": transformers.__version__,
    }
    if previous is not None:
        changed = [key for key, value in metadata.items() if previous.get(key) != value]
        if changed:
            raise ValueError(f"Resume settings differ ({', '.join(changed)}). Use a new output directory.")
    else:
        root.mkdir(parents=True, exist_ok=True)
        atomic_json(metadata_path, {**metadata, "status": "generating"})
    raw_path = root / f"{JSONL_STEM}.jsonl"
    rows = load_resume_rows(raw_path, metadata, tokenizer)
    for row in rows:
        split, index = source_location(row["source_index"], sources)
        example = sources[split][index]
        if (
            row.get("source_split") != split or row.get("source_row_index") != index
            or row.get("prompt_messages") != extract_prompt_messages(example)
            or build_prompt(example, tokenizer) != row["prompt"]
        ):
            raise ValueError(f"Resume prompt/provenance no longer matches source example {row['source_index']}")
    resume_through = rows[-1]["source_index"] if rows else -1
    skipped = 0
    print(f"[distill] UltraChat: {source_rows} source rows across {args.source_splits}; "
          f"resumed {len(rows)}; batch_size=1; completion_budget={args.max_length // 2}; "
          f"{args.dtype}/{args.attn_implementation}", flush=True)
    needs_newline = False
    if raw_path.exists() and raw_path.stat().st_size:
        with raw_path.open("rb") as check:
            check.seek(-1, os.SEEK_END)
            needs_newline = check.read(1) != b"\n"
    with raw_path.open("a", encoding="utf-8") as output:
        if needs_newline:
            output.write("\n")
        offset = 0
        for split, source in sources.items():
            for source_row_index, example in enumerate(source):
                source_index = offset + source_row_index
                if source_index <= resume_through:
                    continue
                if args.max_samples and len(rows) >= args.max_samples:
                    break
                row = generate_row(
                    source_index, example, tokenizer, model,
                    source_split=split, source_row_index=source_row_index,
                    max_prompt_tokens=metadata["max_prompt_tokens"],
                    max_completion_tokens=metadata["max_completion_tokens"], device=args.device,
                )
                if row is None:
                    skipped += 1
                    continue
                output.write(json.dumps(row, ensure_ascii=False) + "\n")
                output.flush()
                os.fsync(output.fileno())
                rows.append(row)
                if len(rows) % args.progress_every == 0:
                    print(f"[distill] {len(rows)} generated; source {source_index + 1}/{source_rows} "
                          f"({split})", flush=True)
            offset += len(source)
            if args.max_samples and len(rows) >= args.max_samples:
                break
    sizes = write_dataset(
        root, rows, args.max_length, args.eval_ratio, args.seed, jsonl_stem=JSONL_STEM,
    )
    atomic_json(metadata_path, {
        **metadata, "status": "complete", "completed_at": datetime.now(timezone.utc).isoformat(),
        "generated_rows": len(rows), "split_rows": sizes,
    })
    print(f"[distill] Saved {len(rows)} UltraChat rows ({sizes['train']} train, {sizes['eval']} held out) "
          f"to {root}; skipped {skipped} empty/overlong prompts in this run", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
